FROM debian:11


RUN apt-get update && apt-get install -y \
	php7.4 \
	php7.4-fpm \
	php7.4-mysql \
	curl \
	mariadb-client

RUN curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar && \
	chmod +x wp-cli.phar && \
	mv wp-cli.phar /usr/local/bin/wp


COPY ./tools/wp_script.sh /
COPY ./conf/www.conf /etc/php/7.4/fpm/pool.d/www.conf

RUN chmod 777 ./wp_script.sh

EXPOSE 9000

ENTRYPOINT ["./wp_script.sh"]

CMD ["php-fpm7.4","-F"]


